### ISSUE TITLE
Update mail server documentation to use clean way to implement TLS versions

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/nf-tower-docs#373]
tower.yml config as per [GEL 3385](https://support.seqera.io/a/tickets/3385):

```yaml
mail:
  smtp:
    host: "your.smtphost.com"
    port: "587"
    auth: "true"
    user: "your_smtp_user"
    password: "your_smtp_password"
    starttls:
      enable: true
      required: true
    ssl:
      protocols: "TLSv1.2"
```
Update mail server docs if necessary.
Modify TLS page (where similar solution is documented with a JVM option.

NOTE: you have have already made this change - I'm losing track of what's struck in PR hell and what we simply haven't done yet.
