### ISSUE TITLE
Update tower.yml docs on installation site to explicitly use TLS v1.2

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/nf-tower-docs#515]
Existing `mail` block in the provided [tower.yml](https://help.tower.nf/23.2/enterprise/_templates/docker/tower.yml) does not include this setting, often breaks as a result of more stringent TLS version demands from the target SMTP endpoint. This is particularly relevant due to [AWS bumping default TLS to v1.2](https://aws.amazon.com/blogs/security/tls-1-2-required-for-aws-endpoints/).

```yaml
# Example of mail block with explicit tls
mail:
  ### from: "${TOWER_CONTACT_EMAIL}"
  smtp:
    ### host: ${TOWER_SMTP_HOST}
    ### port: ${TOWER_SMTP_PORT}
    ### user: ${TOWER_SMTP_USER}
    ### password: ${TOWER_SMTP_PASSWORD}

    auth: true
    starttls:
      enable: true
      required: true
    ssl:
      protocols: "TLSv1.2"
```

## Actions

1. Fix  [tower.yml](https://help.tower.nf/23.2/enterprise/_templates/docker/tower.yml)
2. Fix [configmap](https://help.tower.nf/23.2/enterprise/_templates/k8s/configmap.yml)
